### PR TITLE
Changed uuid dependency and some minor updates

### PR DESCRIPTION
**Pull request by mikalv**
Hi,

I'm meeh from the I2P project. I updated the project a bit. Are you the one also having the i2p npmjs.com package, which I assume is this one? :)

Awesome package by the way!

### CODE REVIEW

**Comment by redhog** [comment]
Hi! Thank you!

I so wasn't aware that someone had published this on npm, and I never bothered... But apparently someone has, and yes, it is this project, including the correct README, link to this github etc!

Thanks for the PR!

**Comment by redhog** [comment]
Would you mind linking to this library from https://geti2p.net/en/docs/api/samv3 btw?

Oh, and the npm uploader seems to be @aakilfernandes. Hi Fernandes!

**Comment by mikalv** [comment]
Cool! Sorry late reply.

@redhog It's added now, https://geti2p.net/en/docs/api/samv3

@aakilfernandes any chance you could push .a new package for npmjs?

**Comment by redhog** [comment]
Thanks!

**Pull request merged**
